spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-yours
    username: postgres
    password: NOVIANTO

  data:
    web:
      pageable:
        one-indexed-parameters: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  security:
    jwt:
      token:
        access-expiration-time: 3600000
        refresh-expiration-time: 86400000
        secret: c8d7c086fe64a415ee1fafe90b1a663ef635f903b129d2bd752af401c817bee0

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG
